version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.2.0-browsers
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run the application
          command: node server.js
          background: true
      - run: sudo npm install -g npm@latest
      - run: npm run test

      # - checkout
      # - node/install:
      #     node-version: "18.2.0"
      # - run:
      #     name: Update NPM
      #     command: "sudo npm install -g npm"
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      # - run:
      #     name: Run the application
      #     command: node server.js
      #     background: true
      # - run:
      #     name: Run tests
      #     command: npm run test
