version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run the application
          command: node server.js
          background: true
      - run:
          name: Run tests
          command: npm run test